### ISSUE TITLE
Publish Command

### ISSUE THREAD

**Issue by SteelAlloy** [nestdotland/nest#7]
#### `nest publish`

1. evaluate the config
2. create a tarball with a uuid in the file name
3. upload the tarball and config to twig
4. twig does it's magic and uploads to arweave
5. twig sends the arweave URLs and the config to the api
6. db gets updated, module is published

#### `nest publish --wallet <path>`

1. evaluate the config
2. create a tarball
3. upload the tarball to arweave and get the file URLs
4. send the arweave URLs and the config to the api
5. db is updated, module is published

### CLI

```sh
nest publish [ version ] [ --git ] [ --pre <id> ] [ --deno <semver>] [ --wallet <path> ] [ --unlisted ]

ARGUMENTS

  version            semver tag or one of "major", "minor", "patch" (default: "patch")

OPTIONS

  --git              use the latest git tag as version (ignored if <version> is provided)
  --pre <id>         publish as a prerelease with optional identifier
  --deno <semver>    semver range for supported deno versions
  --wallet <path>    path to custom arweave wallet
  --unlisted         publish as an unlisted version
```

#### semver behavior

```sh
# say the current version is module@1.0.0

nest publish                      # module@1.0.1
nest publish 1.2.3                # module@1.2.3
nest publish patch                # module@1.0.1
nest publish minor                # module@1.1.0
nest publish major                # module@2.0.0

nest publish --pre                # module@1.0.1-0
nest publish 1.2.3 --pre          # module@1.2.3-0
nest publish patch --pre          # module@1.0.1-0
nest publish minor --pre          # module@1.1.0-0
nest publish major --pre          # module@2.0.0-0

nest publish --pre alpha          # module@1.0.1-alpha.0
nest publish 1.2.3 --pre beta     # module@1.2.3-beta.0
nest publish patch --pre rc       # module@1.0.1-rc.0
nest publish minor --pre asdf     # module@1.1.0-asdf.0
nest publish major --pre pre      # module@1.0.1-pre.0
```

### Notes
- if no versions are published yet and user runs `nest publish` use the version `0.1.0` (unstable)
- when (and only) uploading to `twig`, include the `.nest` directory in the tarball

### ToDo
- [x] create a tarball
- [ ] send the config and uuid to the api
- [ ] upload the tarball to arweave
- [ ] do the twig magic locally
